const $=id=>document.getElementById(id);
const speechBox=$('speech'),robot=$('robot'),nameInput=$('name'),micState=$('micState'),cont=$('continue'),voice=$('voice'),audioBtn=$('audioBtn');
const flow=$('flow'),flowBack=$('flowBack'),flowStep=$('flowStep'),flowTitle=$('flowTitle'),flowText=$('flowText'),choices=$('choices'),flowNext=$('flowNext');
let speaking=false, step=0, selected=null, recognition=null, lessonDone=false;
const state={name:'',companion:'🤖 Robot',language:'English',topic:'Colores'};
function robotState(s){robot.className='robot '+(s||'')}
function setSpeech(title,text){speechBox.innerHTML=`<strong>${title}</strong><span>${text}</span>`}
function pickVoice(){const vs=speechSynthesis.getVoices();return vs.find(v=>/Daniel|Alex|Thomas|Google UK English Male|Microsoft.*David/i.test(v.name))||vs.find(v=>/^es-|^en-/i.test(v.lang))||vs[0]}
function say(text,lang='es-MX',rate=.92){return new Promise(resolve=>{if(!('speechSynthesis'in window)){resolve();return} speaking=true;robotState('talking');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=rate;u.pitch=1;const v=pickVoice();if(v)u.voice=v;let done=false;const finish=()=>{if(done)return;done=true;speaking=false;robotState('');resolve()};u.onend=finish;u.onerror=finish;speechSynthesis.speak(u);setTimeout(finish,Math.min(9000,Math.max(1800,text.length*70/rate)))})}
async function welcome(){setSpeech('¡Hola!','Vamos a tener una gran aventura.<br>¿Cómo te llamas?');await say('¡Hola! Vamos a tener una gran aventura. ¿Cómo te llamas?')}
function showFlow(){flow.classList.remove('hidden');$('nameCard').style.display='none';document.querySelectorAll('.hot').forEach(b=>b.style.pointerEvents='none');renderStep()}
function renderStep(){const data=[
{title:'Elige tu compañero',text:'Tu amiguito te acompañará durante toda la aventura.',items:['🤖 Robot','👧 Niña','👦 Niño','🐶 Animal']},
{title:'Elige tu idioma',text:'En esta aventura aprenderemos un solo idioma.',items:['🇬🇧 English','🇫🇷 Français','🇩🇪 Deutsch','🇮🇹 Italiano']},
{title:'Elige tu aventura',text:'Comenzaremos con una aventura de colores.',items:['🎨 Colores']}
][step];flowStep.textContent=`${step+1} de 3`;flowTitle.textContent=data.title;flowText.textContent=data.text;choices.innerHTML='';flowNext.disabled=true;selected=null;data.items.forEach(item=>{const b=document.createElement('button');b.className='choice';b.textContent=item;b.onclick=()=>{document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=item;flowNext.disabled=false};choices.appendChild(b)})}
flowNext.onclick=async()=>{if(!selected)return;if(step===0)state.companion=selected;if(step===1)state.language=selected.replace(/^\S+\s/,'');if(step===2){state.topic='Colores';startLesson();return}step++;renderStep();await say(step===1?'Ahora elige el idioma de la aventura.':'¡Muy bien! Ahora vamos a elegir qué aprenderemos.')}
flowBack.onclick=()=>{if(step===0){flow.classList.add('hidden');$('nameCard').style.display='block';document.querySelectorAll('.hot').forEach(b=>b.style.pointerEvents='');return}step--;renderStep()};
cont.onclick=async()=>{if(speaking)return;const n=nameInput.value.trim();if(!n){setSpeech('¡Cuéntame tu nombre! 👋','');robotState('excited');await say('¿Cómo te llamas?');return}state.name=n;setSpeech(`¡Guau, ${n}! 🤩`,'¡Qué alegría conocerte!');robotState('excited');await say(`¡Guau, ${n}! ¡Qué alegría conocerte! Vamos a comenzar nuestra aventura.`);showFlow()};
audioBtn.onclick=()=>say(`¡Hola ${state.name||'explorador'}! Soy tu compañero de aventura. ¡Toca continuar cuando estés listo!`);
voice.onclick=async()=>{if(speaking)return;const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){micState.textContent='El navegador no permite reconocimiento de voz. Puedes escribir tu nombre.';return}try{if(navigator.mediaDevices?.getUserMedia){const s=await navigator.mediaDevices.getUserMedia({audio:true});s.getTracks().forEach(t=>t.stop());await new Promise(r=>setTimeout(r,300))}}catch(e){}const r=new SR();recognition=r;r.lang='es-MX';r.continuous=false;r.interimResults=false;r.maxAlternatives=5;micState.textContent='🟢 Micrófono activado. ¡Ahora puedes hablar!';robotState('listening');voice.disabled=true;r.onresult=e=>{const t=e.results[0][0].transcript.trim();nameInput.value=t;state.name=t;setSpeech(`¡Guau, ${t}! 🤩`,'¡Qué alegría conocerte!');robotState('excited');say(`¡Guau, ${t}! ¡Qué alegría conocerte! Vamos a comenzar nuestra aventura.`)};r.onerror=e=>{robotState('');micState.textContent=e.error==='not-allowed'?'🎙️ Permite el micrófono en Safari.':'No pude escucharte. Puedes intentarlo otra vez.';voice.disabled=false};r.onend=()=>{robotState('');voice.disabled=false};try{r.start()}catch(e){robotState('');voice.disabled=false}};
function lessonShell(){flowTitle.textContent='Primera aventura: Colores';flowText.textContent=`¡${state.name}! Vamos a descubrir nuestra primera palabra en ${state.language}.`;flowStep.textContent='Aventura 1';choices.innerHTML=`<div class="lesson-card"><div class="apple">🍎</div><div class="new-word">NUEVA PALABRA</div><div class="word">RED</div><div class="meaning">rojo</div><div class="lesson-actions"><button class="listen-word" id="listenWord">🔊 Escuchar RED</button><button class="repeat-word" id="repeatWord">🎙️ Repetir RED</button></div><div class="status" id="lessonStatus">Escucha primero y después dilo tú.</div><button class="game-main-btn" id="goGame">🎮 Ir al juego →</button></div>`;flowNext.style.display='none';flowBack.style.display='block';$('listenWord').onclick=()=>playIntroColor();$('repeatWord').onclick=()=>listenRed();$('goGame').onclick=()=>startGame()}
async function playIntroColor(){setSpeech('🍎 ¡Mira lo que encontré!','Una manzana roja.');await say(`¡Guau, ${state.name}! ¡Mira lo que encontré! ¡Una manzana!`);await say('La manzana es roja. Rojo es el color que vamos a aprender.');await say('En inglés, rojo se dice RED. Escucha: RED.');await say('RED','en-US',.75);$('lessonStatus').textContent='🎙️ Ahora tú: toca Repetir RED y dilo conmigo.'}
async function listenRed(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('lessonStatus').textContent='Este navegador no permite reconocer voz. Puedes continuar con el juego.';return}const btn=$('repeatWord');btn.disabled=true;$('lessonStatus').textContent='🎙️ Activando el micrófono…';try{if(navigator.mediaDevices?.getUserMedia){const s=await navigator.mediaDevices.getUserMedia({audio:true});s.getTracks().forEach(t=>t.stop());await new Promise(r=>setTimeout(r,350))}}catch(e){}const r=new SR();recognition=r;r.lang='en-US';r.continuous=false;r.interimResults=false;r.maxAlternatives=10;let finished=false;const finish=()=>{if(finished)return;finished=true;btn.disabled=false;robotState('');clearTimeout(timer)};r.onstart=()=>{$('lessonStatus').textContent='👂 Te escucho… di RED';robotState('listening')};r.onresult=e=>{const arr=[...e.results[0]].map(x=>x.transcript.toLowerCase().trim());const ok=arr.some(t=>/\bred\b|read|reed|ret|re/.test(t));if(ok){$('lessonStatus').textContent='🎉 ¡Excelente! Reconocí RED.';lessonDone=true;robotState('excited');setSpeech('🎉 ¡Excelente!','¡Lo dijiste muy bien! Ahora vamos a jugar.');say('¡Excelente! Lo dijiste muy bien. Ahora vamos a jugar.')}else{$('lessonStatus').textContent='Casi. Escucha otra vez y prueba RED.'}finish()};r.onerror=e=>{$('lessonStatus').textContent=e.error==='not-allowed'?'🎙️ Permite el micrófono en Safari.':'No pude escucharte. Puedes intentarlo otra vez.';finish()};r.onend=finish;const timer=setTimeout(()=>{try{r.abort()}catch(e){}$('lessonStatus').textContent='⏳ No escuché una respuesta. Inténtalo otra vez.';finish()},8000);try{r.start()}catch(e){clearTimeout(timer);finish();$('lessonStatus').textContent='No pude activar el micrófono.'}}
function startLesson(){flow.classList.remove('hidden');flowTitle.textContent='';flowText.textContent='';flowStep.textContent='';flowBack.style.display='block';lessonShell();setSpeech('🍎 ¡Vamos a aprender RED!','');say(`¡${state.name}! Nuestra primera aventura será aprender colores. ¡Vamos a descubrir RED!`)}
function startGame(){flowStep.textContent='Juego 1';flowTitle.textContent='🎮 Encuentra RED';flowText.textContent='Busca y toca todos los objetos de color rojo.';choices.innerHTML=`<div class="game-card"><h3>🔴 ¿Dónde está el rojo?</h3><div class="game-instruction">Toca un objeto rojo. ¡Hay uno correcto!</div><div class="objects"><button class="object red" data-red="1">🍎</button><button class="object" data-red="0">🦋</button><button class="object" data-red="0">🟢</button><button class="object" data-red="0">🌊</button></div><div class="status" id="gameStatus">Pista: la manzana es RED.</div><button class="game-main-btn" id="nextChallenge">🎙️ Responder: ¿qué color es la manzana?</button></div>`;document.querySelectorAll('.object').forEach(o=>o.onclick=()=>{if(o.dataset.red==='1'){o.classList.add('correct');$('gameStatus').textContent='🎉 ¡Sí! La manzana es RED.';say('¡Sí! ¡Encontraste el objeto rojo! Es RED.');document.querySelectorAll('.object').forEach(x=>x.disabled=true)}else{o.classList.add('wrong');$('gameStatus').textContent='Casi. Busca el objeto rojo.';setTimeout(()=>o.classList.remove('wrong'),350)}});$('nextChallenge').onclick=challengeVoice}
async function challengeVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){finishGame();return}const btn=$('nextChallenge');btn.disabled=true;$('gameStatus').textContent='🎙️ Di el color de la manzana en inglés.';setSpeech('🎙️ Ahora tú','¿Qué color es la manzana?');await say('¿Qué color es la manzana? Dilo en inglés.');try{if(navigator.mediaDevices?.getUserMedia){const s=await navigator.mediaDevices.getUserMedia({audio:true});s.getTracks().forEach(t=>t.stop());await new Promise(r=>setTimeout(r,300))}}catch(e){}const r=new SR();r.lang='en-US';r.continuous=false;r.interimResults=false;r.maxAlternatives=10;let done=false;const finish=()=>{if(done)return;done=true;btn.disabled=false};r.onstart=()=>$('gameStatus').textContent='👂 Te escucho…';r.onresult=e=>{const t=[...e.results[0]].map(x=>x.transcript.toLowerCase());if(t.some(x=>/\bred\b|read|reed|ret|re/.test(x))){$('gameStatus').textContent='⭐ ¡Perfecto! RED.';say('¡Perfecto! Has demostrado que recuerdas RED. ¡Ganaste una estrella!').then(finishGame)}else{$('gameStatus').textContent='Puedes intentarlo otra vez. Recuerda: RED.';finish()}};r.onerror=()=>{ $('gameStatus').textContent='No pude escucharte. Inténtalo otra vez.';finish()};r.onend=finish;try{r.start()}catch(e){finish()}}
function finishGame(){flowTitle.textContent='⭐ ¡Aventura completada!';flowText.textContent='Aprendiste tu primera palabra en inglés.';choices.innerHTML='<div class="lesson-card"><div class="reward">🌟 ⭐ 🌟</div><h3>¡Excelente, explorador!</h3><p>Escuchaste, repetiste, reconociste y jugaste con RED.</p><button class="game-main-btn" id="again">🔁 Jugar otra vez</button></div>';flowNext.style.display='none';$('again').onclick=startGame;setSpeech('🏆 ¡Lo lograste!','¡Aprendiste RED!')}
$('juega').onclick=()=>{setSpeech('🎮 ¡Sí!','¡Sí! Vamos a jugar.');say('¡Sí! Vamos a jugar.')};$('aprende').onclick=()=>{setSpeech('📚 ¡Sí!','¡Sí! Vamos a aprender.');say('¡Sí! Vamos a aprender.')};$('explora').onclick=()=>{setSpeech('🧭 ¡Sí!','¡Sí! Vamos a explorar.');say('¡Sí! Vamos a explorar.')};$('crece').onclick=()=>{setSpeech('🌱 ¡Sí!','¡Sí! Vamos a crecer y descubrir cosas nuevas.');say('¡Sí! Vamos a crecer y descubrir cosas nuevas.')};$('lang').onclick=()=>{setSpeech('🌎 Idioma','El idioma de esta aventura se elige al comenzar.');say('El idioma de la aventura se elige al comenzar.')};
window.speechSynthesis?.addEventListener('voiceschanged',()=>{});welcome();
